import { Bot, Sparkles, AlertTriangle } from 'lucide-react'

export default function AIAdvisoryCard({ advisory, loading }) {
    if (loading) {
        return (
            <div className="bg-white dark:bg-dark-surface rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 p-6 animate-pulse">
                <div className="h-6 bg-gray-200 dark:bg-gray-700 rounded w-1/3 mb-4"></div>
                <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4 mb-2"></div>
                <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-full mb-2"></div>
                <div className="h-4 bg-gray-200 dark:bg-gray-700 rounded w-5/6"></div>
            </div>
        )
    }

    if (!advisory) return null

    return (
        <div className="relative overflow-hidden bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-950/30 rounded-xl shadow-lg border border-indigo-100 dark:border-indigo-900 p-6">
            {/* Decorative background elements */}
            <div className="absolute top-0 right-0 -mr-10 -mt-10 w-32 h-32 bg-indigo-500/10 rounded-full blur-2xl"></div>
            <div className="absolute bottom-0 left-0 -ml-10 -mb-10 w-32 h-32 bg-purple-500/10 rounded-full blur-2xl"></div>

            <div className="relative z-10">
                <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-indigo-100 dark:bg-indigo-900/50 rounded-lg">
                        <Sparkles className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
                    </div>
                    <h3 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400">
                        AI Agronomist Insights
                    </h3>
                </div>

                <div className="prose prose-indigo dark:prose-invert max-w-none text-indigo-900 dark:text-indigo-100">
                    <div className="whitespace-pre-wrap leading-relaxed">
                        {advisory}
                    </div>
                </div>

                <div className="mt-4 pt-4 border-t border-indigo-200 dark:border-indigo-800 flex items-center gap-2 text-xs text-indigo-600 dark:text-indigo-400">
                    <Bot className="w-4 h-4" />
                    <span>Generated by Advanced AgroAI Engine</span>
                </div>
            </div>
        </div>
    )
}
